### ISSUE TITLE
"No video files found in the input directory" for folder containing .mkv videos

### ISSUE THREAD

**Issue by Pudzianos** [sakthivelj/video2image#1]
Hello, using folder as input which contains .mkv files returns "No video files found in the input directory".
Would it be possible to make it also work for .mkv videos? :)

**Comment by Pudzianos** [comment]
Changing .mp4 to .mkv seems working for now
![pycharm64_kCU3mXGQoK](https://github.com/sakthivelj/video2image/assets/127506462/1738fedc-d099-4fea-a513-62c514f7aee4)

**Comment by sakthivelj** [comment]
@Pudzianos Thank you for bringing up the issue. I will update the code to support all video formats.
